### PR TITLE
[Draft] Add github ci workflow

### PR DESCRIPTION
**Pull request by naijab**
## Feature
- it run test when pull request to main or develop
- build release when tag version 
- deploy to npmjs.com can install with `npx levis`
- deploy to homebrew for macOS version after build release completed

## Setup Codecov
- set secret **CODECOV_TOKEN** value is from codecov
   - add badge from codecov settings

## Setup for deploying to NPM.js
- set secret **NPM_TOKEN** see how to from [docs](https://docs.npmjs.com/creating-and-viewing-access-tokens/)

## Setup updating to homebrew formula
- kubeops create repo name **kubeopsskills/homebrew-levis** and I will create pull request formula again
- set secret **BREW_TOKEN_TAP** with personal access token (require full repository permission)

### CODE REVIEW

**Comment by sikiryl** [comment]
LGTM, รายละเอียดค่อนข้างครบครับ เดี๋ยวมา discuss กันเรื่อง homebrew ต่อ

**Comment by sikiryl** [comment]
@naijab 
I have created this repo [kubeopsskills/homebrew-levis](https://github.com/kubeopsskills/homebrew-levis)
https://github.com/kubeopsskills/homebrew-levis

**Comment by naijab** [comment]
> @naijab I have created this repo [kubeopsskills/homebrew-levis](https://github.com/kubeopsskills/homebrew-levis) https://github.com/kubeopsskills/homebrew-levis

ok I will create pr for formula class

**Comment by naijab** [comment]
> @naijab I have created this repo [kubeopsskills/homebrew-levis](https://github.com/kubeopsskills/homebrew-levis) https://github.com/kubeopsskills/homebrew-levis

@Sikiryl  @dmakeroam 

I had create pr for homebrew levis: https://github.com/kubeopsskills/homebrew-levis/pull/1

**Comment by sikiryl** [comment]
@naijab 
อาจจะต้องแยก commit เป็นเรื่องๆ แล้วเปิด PR มาใหม่ครับ

**Pull request closed without merging**
